# Generated by Django 3.0.3 on 2021-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
