# Generated by Django 3.0.3 on 2021-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0003_userprofileinfo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
