# Generated by Django 3.0.3 on 2021-04-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0004_auto_20210425_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jobfair_app.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('freelancer', 'freelancer'), ('employer', 'employer')], default='freelancer', max_length=100),
        ),
    ]
