# Generated by Django 3.0.3 on 2021-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0008_auto_20210425_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
