# Generated by Django 3.0.3 on 2021-04-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0009_auto_20210425_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
