# Generated by Django 3.0.3 on 2021-04-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0010_delete_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
    ]
