# Generated by Django 3.0.3 on 2021-04-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0011_remove_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(default='', max_length=500),
        ),
    ]
