# Generated by Django 3.2.6 on 2021-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfair_app', '0012_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='rating',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('FLR', 'Freelancer'), ('EMP', 'Employer')], default='FLR', max_length=10),
        ),
    ]
